version: "3.1"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./mydatabase:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: trans_db

  api:
    image: node:18-alpine
    container_name: api
    restart: always
    ports:
      - 6006:6006
      - 6005:6005
      - 3030:3030
      - 5555:5555
    links:
      - db
    volumes:
      - ./api:/app
    depends_on:
      - db
    command: "sh -c 'chmod -R 777 /root && cd /app && npm install && npx prisma migrate dev && npm run start:dev'"

  app:
    image: node:18-alpine
    container_name: app
    restart: always
    ports:
      - 3000:3000
    links:
      - db
    volumes:
      - ./app:/app
    depends_on:
      - api
    command: "sh -c 'chmod -R 777 /root && cd /app && npm install && npm run start'"
